### ISSUE TITLE
Exported function documentation

### ISSUE THREAD

**Issue by slwu89** [kavir1698/EvoDynamics.jl#37]
Hi @kavir1698, this issue is related to the JOSS review at https://github.com/openjournals/joss-reviews/issues/4775

I see that `EvoDynamics.runmodel` is documented in the online docs. However the two other exported functions `load_parameters` and `model_initiation` are not in the online docs, I suggest adding docstrings to exported functions if users are going to interact with them.

**Comment by kavir1698** [comment]
Hi @slwu89,
Thanks for this feedback. I have now added docstrings to the `load_parameters` and `model_initiation` functions and have included these docstrings in the online docs, on the tutorial page.

**Comment by slwu89** [comment]
Great! I see it was resolved in this commit https://github.com/kavir1698/EvoDynamics.jl/commit/c16443c5183ca7d84ec46ba14b4af108f185e44e 

I'll close this issue.
