### ISSUE TITLE
Make the model more general

### ISSUE THREAD

**Issue by kavir1698** [kavir1698/EvoDynamics.jl#5]
Currently, each agents has fields `B`, `y`, and `z`. `y` is a vector of floating numbers that specifies the importance of each trait. `B` is a binary matrix of size `length(z) * length(y)`. It specifies for each phenotype, which genes are involved. Finally, `z=By`.

The limitation of this formulation is that a single gene, for example, `y[1]`, has the same fixed amount of contribution to different phenotypes in which it is involved.

I suggest that we collapse`B` and `y` into a new matric `A` (`size(A) == size(B)`) where each element of `A` specified the contribution of a gene to a phenotype. With that, we can have a single gene contributing to different phenotypes differently. It will also increase the performance of the model.

**Comment by kavir1698** [comment]
Dear @melian009, what do you think about this?

**Comment by melian009** [comment]
Dear Ali,

Introducing A generalizes the effect of a gene on each trait  -- and this is great! The vector of effects with all numbers equal is the previous model -- variable numbers introduce different effects -- notice this introduction can also consider epistasis --  the effect of a gene on a specific trait can also be sampled from gene the interaction matrix (not explicit now) and not only sampled from a iid values in matrix A. 

A big hug


Carlos

**Comment by melian009** [comment]
Dear Ali,

We have been thinking in someways to account for the epistasis and pleiotropy matrix simultaneously -- I will commit to cocon these days with the writing about it

**Comment by kavir1698** [comment]
Thank you Carlos. I will work on it.
